plugins {
	id 'java-library'
	id 'maven-publish'
}

dependencies {
	implementation files("libs/AndroidField.jar")
}

jar {
	from(configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) })
}

publishing {
	publications {
		maven(MavenPublication) {
			from components.java
			artifactId = 'magic-accessor-annotations'
		}
	}
}
