plugins {
	id 'java-library'
	id 'maven-publish'
}

dependencies {
	api project(':magic-accessor:annotations')

	def asmVersion = '9.9.1'
	implementation "org.ow2.asm:asm:$asmVersion"
	implementation "org.ow2.asm:asm-commons:$asmVersion"
	implementation "org.ow2.asm:asm-tree:$asmVersion"

	testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
	options.compilerArgs += ['-Xlint:none', '-nowarn']
}

jar {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	manifest {
		attributes 'Main-Class': 'hope.magic.js.cli.Main'
	}
	from {
		configurations.runtimeClasspath.findAll { it.name.startsWith("asm-") }.collect { zipTree(it) }
	}
}

tasks.register('magicjs', JavaExec) {
	classpath = sourceSets.main.runtimeClasspath
	mainClass = 'hope.magic.js.cli.Main'
	if (project.hasProperty('args')) {
		args = Eval.me(project.property('args').toString())
	}
}

publishing {
	publications {
		maven(MavenPublication) {
			from components.java
			artifactId = 'magic-accessor-js'
		}
	}
}
