package modtools.ui;

import modtools.annotations.ContentInit;
import modtools.content.*;
import modtools.content.debug.*;
import modtools.content.ui.*;
import modtools.content.world.*;

@SuppressWarnings("unused")
@ContentInit
public class Contents {
	public static SettingsUI    settings_ui;
	public static Tester        tester;
	public static Selection     selection;
	public static ShowUIList    show_ui_list;
	public static UnitSpawn     unit_spawn;
	public static LogDisplay    log_display;
	public static ContentList   content_list;
	public static ReviewElement review_element;
	// public static DesignContent design_content;
	public static Executor      executor;
	public static KeyCodeSetter key_code_setter;
	public static Pause         pause;
	public static WindowManager window_manager;

	/**
	 * generated by annotation
	 * @see ContentInit
	 */
	public static void load() { }
}
