name: Build project

on: 
  push:
  workflow_dispatch:

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin

    - name: Get latest release version
      id: get_version
      run: |
        latest_version=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
        echo "LATEST_VERSION=${latest_version}" >> $GITHUB_ENV

    - name: Build mod jar
      run: |
        chmod 777 gradlew
        ./gradlew ZCompileAll

    - name: Rename built jar file
      run: |
        mv build/libs/${{ github.event.repository.name }}-deploy.jar build/libs/${{ github.event.repository.name }}-${{ env.LATEST_VERSION }}-deploy.jar

    - name: Upload built jar file
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ${{ github.event.repository.name }}-${{ env.LATEST_VERSION }}
        path: build/libs/${{ github.event.repository.name }}-deploy.jar
        if-no-files-found: ignore
